### ISSUE TITLE
Is there a way to configure the size of the map appearing in a notebook cell ?

### ISSUE THREAD

**Issue by sergesvr** [pbugnion/gmaps#108]
Is it possible to define the height and width at the moment ?

**Comment by pbugnion** [comment]
Pass `height` and `width` arguments to `Map`:

```
data = gmaps.datasets.load_dataset('taxi_rides')
weights = [random.random() for d in data]
m = gmaps.Map(width="100px", height="200px")
heatmap = gmaps.heatmap_layer(data, weights=None, opacity=0.5)
m.add_layer(heatmap)
m
```

<img width="680" alt="screen shot 2017-03-02 at 21 14 01" src="https://cloud.githubusercontent.com/assets/1392879/23527268/31d443c8-ff8d-11e6-8f14-9942fd8ca72f.png">

**Comment by pbugnion** [comment]
Closing in favour of #109. Feel free to carry on asking on this thread if you have more questions though.

**Comment by ctmartins** [comment]
Tried changing the size by doing:
```
def generate_heat_map(df):
    gmaps.configure(api_key=config.api_key)

    lat_list = []
    long_list = []
    for index, row in df.iterrows():
        long_list.append(row['longitude'])
        lat_list.append(row['latitude'])
            
    locations = zip(lat_list, long_list)

    m = gmaps.Map(align_self = 'center',width="100%",height='100%')
    m.add_layer(gmaps.heatmap_layer(locations))

    return m
```
But it doesn't change the size when saving to a html file.
I am saving like this:
```
embed_minimal_html(html_heatmap_file, views=[heat_map])
```

**Comment by pbugnion** [comment]
@ctmartins I presume you are trying to get a full screen output?

If so, the following works here:

```
m = gmaps.Map(width='100%', height='100vh', layout={'height': '100vh'})
```

Annoyingly, you have to set the map height twice -- once as a keyword argument to `gmaps.Map`, and once as part of the `layout` dictionary. Eventually, the plan is to remove the keyword argument in `gmaps.Map` (this is left over from a previous version of ipywidgets).

Note also that I use `vh` as a unit. `100vh` is a 100% of the browser height. I find that it's easier to understand than `100%`, which means `100%` of the parent container's height.

**Comment by ctmartins** [comment]
Thank you, very much. That was exactly what I needed and worked perfectly.
