### ISSUE TITLE
Map disappears when jupyter notebook is downloaded as html

### ISSUE THREAD

**Issue by updiversity** [pbugnion/gmaps#110]
If i download my notebook as html, then by opening the html file, the google map is not visible anymore.

However, if i use other libraries such as ipyleaflet or folium, then the maps are maintained in the exported notebook.

what would be the solution to make that happen as well with gmaps ?

**Comment by pbugnion** [comment]
As far as I understand, this is only possible with the newest version of ipywidgets (6.0.0) which has only just come out -- I'd be keen to know if ipyleaflet supported this before. 

I have not ported gmaps to the new ipywidgets yet. It'll almost certainly need changes. PRs welcome, as always.

**Comment by pbugnion** [comment]
In fact, this was definitely not working in ipyleaflets prior to ipywidgets 6.0.0:

https://github.com/ellisonbg/ipyleaflet/issues/36

**Comment by pbugnion** [comment]
This now works (as of release 0.5.0)
