### ISSUE TITLE
Bicycling

### ISSUE THREAD

**Issue by ericgcoker** [pbugnion/gmaps#119]
When visiting maps.google.com. There is an option to show Bicycle trails/maps. Is there any way to show this on the tiles of a Symbol_layer map?

**Comment by pbugnion** [comment]
Thanks for the question!

This is currently not possible. Probably the right way to add this to *jupyter-gmaps* is to create a new layer. A good starting point for this would be the code for the [directions layer](https://github.com/pbugnion/gmaps/blob/master/gmaps/directions.py).

**Comment by pbugnion** [comment]
Closed by PR #163.
