### ISSUE TITLE
It's posible draw distance vectors between points?

### ISSUE THREAD

**Issue by malliwi88** [pbugnion/gmaps#120]
I want to draw lines between points with its respective distances
like as google maps do it

![seleccion_026](https://cloud.githubusercontent.com/assets/5307894/24468198/1c7977be-147d-11e7-8c1c-c743d2d6f9bb.png)

It's posible make it? How can i do it?

Any help it's appreciated.

**Comment by pbugnion** [comment]
Thanks for the question. It might help to have a bit more context here. 

> I want to draw lines between points with its respective distances

How do you want to specify the points? By clicking on a map? In Python?

> with its respective distances

Do you mean straight line distances? If you have the latitude and longitude, you should be able to calculate the straight line distance between two points easily. I expect there are standard packages, but it's not really in scope for *jupyter-gmaps*. If you don't have the latitude and longitude but have some form of geocode, you can use the Google Maps geocoding API (maybe via [this](https://pypi.python.org/pypi/python-gmaps) package) to get latitudes and longitudes.

> like as google maps do it

I might be wrong, but that picture doesn't look like it's from Google Maps, unless I'm missing something?

**Comment by Nickl55** [comment]
Hi
 
I want to do the same thing, i want straight line distances between 2 points, i have longitude and latitude and if it is posible, to put a lable right below the line with the distance between them. I just dont know how to draw that line with the distance.

Thank you.

**Comment by pbugnion** [comment]
Thanks very much for the feedback. This is not currently possible with *jupyter-gmaps*. I've opened an issue (issue #126) that should address this.

**Comment by pbugnion** [comment]
With *jupyter-gmaps* 0.7.0, you can now integrate gmaps into widget-based applications. The following lets us draw lines on the map and print the distance of each line in a text box below the map:

```python
import ipywidgets as widgets
import geopy.distance
import geopy.format
import gmaps

API_KEY = "AIza..."
gmaps.configure(api_key=API_KEY)

class DistanceCalculculator(object):
    
    def __init__(self):
        self._figure = gmaps.figure()
        self._drawing = gmaps.drawing_layer(show_controls=False, mode='LINE')
        self._drawing.on_new_feature(self._new_feature_callback)
        self._figure.add_layer(self._drawing)
        self._start_box = widgets.Text(
            description='start: ',
            disabled=True,
            layout={'width': '30%', 'margin': '10px 0 0 0'}
        )
        self._end_box = widgets.Text(
            description='end: ',
            disabled=True,
            layout={'width': '30%', 'margin': '10px 0 0 0'}
        )
        self._distance_box = widgets.Text(
            description='distance: ',
            disabled=True,
            layout={'width': '30%', 'margin': '10px 0 0 0'}
        )
        self._geocoder = geopy.geocoders.GoogleV3(api_key=API_KEY)
        _info_container = widgets.HBox([self._start_box, self._end_box, self._distance_box])
        self._container = widgets.VBox([self._figure, _info_container])
        
    def _format_location(self, location):
        latitude, longitude = location
        fmt = '%(degrees)d%(deg)s° %(minutes)dm'
        latitude_str = geopy.format.format_degrees(latitude, fmt=fmt) + ' N' if abs(latitude) > 0.0 else ' S'
        longitude_str = geopy.format.format_degrees(longitude, fmt=fmt) + ' E' if abs(longitude) > 0.0 else ' W'
        return '{}, {}'.format(latitude_str, longitude_str)
        
    def _clear_info(self):
        self._distance_box.value = ''
        
    def _get_distance_km(self, start_location, end_location):
        return geopy.distance.great_circle(start_location, end_location).kilometers
        
    def _set_info(self, start_location, end_location):
        distance_km = self._get_distance_km(start_location, end_location)
        self._distance_box.value = '{:.2f} km'.format(distance_km)
        self._start_box.value = self._format_location(start_location)
        self._end_box.value = self._format_location(end_location)
        
    def _new_feature_callback(self, feature):
        try:
            start_location = feature.start
            end_location = feature.end
        except AttributeError:
            return # Not a line

        # Clear distance box to signify to the user that something is happening
        self._clear_info()

        # Remove all markers other than the one that has just been added.
        self._drawing.features = [feature]

        # Compute the address and display it
        self._set_info(start_location, end_location)
        
    def render(self):
        return self._container
    
DistanceCalculculator().render()
```

![giphy 1](https://user-images.githubusercontent.com/1392879/32690728-0416d788-c6f3-11e7-829c-02742bd7d921.gif)
