### ISSUE TITLE
Can't get it working with simple example.

### ISSUE THREAD

**Issue by meskis** [pbugnion/gmaps#125]
I'm trying to set it up, but error is massively non-descriptive. I'm using Jupyter to run it.

```
import gmaps
import gmaps.datasets
gmaps.configure(api_key="AI...") # Your Google API key
locations = gmaps.datasets.load_dataset("taxi_rides")

m = gmaps.Map()
m.add_layer(gmaps.heatmap_layer(locations))
m
```

Jupyter results in:

```
Could not create model:
Model name	PlainmapModel
Model module	jupyter-gmaps
Model module version	*
Script error for "jupyter-gmaps" http://requirejs.org/docs/errors.html#scripterror
```

**Comment by pbugnion** [comment]
Thanks for raising an issue!

This seems very much like issue #122. Can you try that?

**Comment by pbugnion** [comment]
The error is indeed not useful -- I think this is the generic error that ipywidget raises when it completely fails to load a script.

**Comment by meskis** [comment]
Yes, I've managed to get it working by enabling two extensions:
```
jupyter nbextension enable --py --sys-prefix gmaps
jupyter nbextension enable --py --sys-prefix widgetsnbextension
```

Thanks!

**Comment by pbugnion** [comment]
Great!

For anyone else coming across this: after you've loaded the extensions, you need to refresh the browser page running the notebook and restart the jupyter kernel for the changes to take effect.
