### ISSUE TITLE
Ability to draw polygons and lines on the map

### ISSUE THREAD

**Issue by pbugnion** [pbugnion/gmaps#126]
It would be useful to have a layer for drawing polylines and shapes. Anyone wanting to implement this should look at [this](https://developers.google.com/maps/documentation/javascript/shapes) guide for the google maps javascript API, and at how the marker layer is implemented.

The most obvious implementation of this would be to add a `Polygon` layer to gmaps that lets users add arbitrary polygons and polylines. I would imagine that the implementation (at least at the Python level) would be very similar to the `Marker` layer.

**Comment by Jelstra95** [comment]
It would be useful to plot lines between sets of coordinates (for example for cars/ships at different time intervals). Maybe also colouring the lines with to show speed/acceleration.

I'm unhappy to still not to be able to develop such a thing.

**Comment by pbugnion** [comment]
Some of this is now possible. See the [documentation](http://jupyter-gmaps.readthedocs.io/en/latest/tutorial.html#drawing-markers-lines-and-polygons) on drawing lines.

The line colour and style still cannot be customised, though. See issue #205.

**Comment by mandythakur** [comment]
i want to plot polygons of 100 mtrs and den show the data in them perc or cluster .I have huge dateset of lat and longs and want to make hexbins

**Comment by pbugnion** [comment]
> i want to plot polygons of 100 mtrs and den show the data in them perc or cluster .I have huge dateset of lat and longs and want to make hexbins

I recommend reading [the docs section on polygons](http://jupyter-gmaps.readthedocs.io/en/latest/tutorial.html#drawing-markers-lines-and-polygons).

**Comment by mandythakur** [comment]
Hey pascal i didnt get much idea from this so i want to know that i have set of lat and long of different user in any city and i want to plot polygons  in every areas of city  to check area demand but i dnt knw what all lat/longs would be the co ordinates of my polygons like polygons should be around 100 to 200 mtrs. Any solution to this bro
