### ISSUE TITLE
Customise Directions Layer rendering

### ISSUE THREAD

**Issue by Nickl55** [pbugnion/gmaps#132]
Is it possible to change the color of a direction layer? Because i see they are only blue, i want to have for example 2 blue and 1 green, can this be made?.

**Comment by pbugnion** [comment]
Thanks for raising this!

It's definitely not possible at the moment. PRs for this are welcome! Anyone interested in implementing this should look at exposing the [DirectionsRendererOptions](https://developers.google.com/maps/documentation/javascript/reference#DirectionsRendererOptions) through the widget.

**Comment by Nickl55** [comment]
Hi Pascal:

Thanks for answering, i suppose the only way its modifying the library.

I had another question i hope you could help me i've tried to use the code
inside a method, but when i try to print the map it just doesnt print
anything, only works when i do it outside i have tried to return the map
from the method but still doesnt work, i dont know if i am doing something
wrong, could you help me? here is the code.

import gmaps
import gmaps.datasets
gmaps.configure(api_key="AI...")

m = gmaps.Map()

def generate_map():
    geneva = (46.2, 6.1)
    montreux = (46.4, 6.9)
    zurich = (47.4, 8.5)
    geneva2zurich = gmaps.directions_layer(geneva, zurich)
    m.add_layer(geneva2zurich)
    return m
def mapa ():
    m=generate_map()
    m
mapa()

**Comment by pbugnion** [comment]
Edited the last comment since it exactly duplicated a question in issue #133 .

**Comment by pbugnion** [comment]
xref: PR #153 adds additional options to the directions layer, though not rendering directly.

**Comment by pbugnion** [comment]
Closed by PR #247 . This is available in version 0.8.0.
