### ISSUE TITLE
Inside a Method

### ISSUE THREAD

**Issue by Nickl55** [pbugnion/gmaps#133]
Hi Pascal:

I've tried to use the code inside a method, but when i try to print the map it just doesnt print anything and keeps running, only works when i do it outside i have tried to return the map from the method but still doesnt work, i dont know if i am doing something wrong, could you help me? here is the code.

```python
import gmaps
import gmaps.datasets
gmaps.configure(api_key="AI...")

m = gmaps.Map()

def generate_map():
    geneva = (46.2, 6.1)
    montreux = (46.4, 6.9)
    zurich = (47.4, 8.5)
    geneva2zurich = gmaps.directions_layer(geneva, zurich)
    m.add_layer(geneva2zurich)
    return m

def mapa ():
    m = generate_map()
    m

mapa()
```

**Comment by pbugnion** [comment]
Thanks for raising the issue. Your `mapa` function needs to actually *return* the map:

```python
def mapa ():
    m = generate_map()
    return m
```

... though at this point you might as well use `generate_map` directly:

<img width="1115" alt="screen shot 2017-05-14 at 06 57 43" src="https://cloud.githubusercontent.com/assets/1392879/26031624/afd74b62-3872-11e7-8c26-38bb80f0c9d6.png">

For reference, Jupyter notebooks work by displaying the last expression in a cell. That's why all the code examples have a single `m` at the end: the notebook takes that expression and evaluates it, which injects a widget into the cell output. If the last output of your cell is a call to `generate_map`, the notebook will display the return value of that.

**Comment by Nickl55** [comment]
Yes i see you are right, thank you very much, sorry for the ignorance at
python im just new at this, i need to call that fuction using a button, so
when the user clicks it. it can prints the map, somehow i need it to print
that return m

i understand buttons don't return anything i just dont know how to print m

mapa = googlemaps.Client(key='AIza')
gmaps.configure(api_key="AIzaS")

def mostrar_mapa() :
    m = gmaps.Map()
    opcion = int(opcion1.get())
    if opcion == 1:
        file=open('Ciudades.csv','r')
        contenido=file.readlines()
        k=0
        for i in range (len(contenido)):
            k=k+1

        k=k-1

        i=0
        for i in range (len(contenido)):
            ciudades.append(contenido[i])

        for ciudad in ciudades:
            single_place = ciudad.split('/')[0]
            geocode_result = mapa.geocode(single_place)[0]
            lat=(geocode_result['geometry']['location']['lat'])
            lng=(geocode_result['geometry']['location']['lng'])
            latitud.append(lat)
            longitud.append(lng)

        i=0
        for i in range(len(latitud)-1):
                a = (latitud[i], longitud[i])
                b = (latitud[i+1], longitud[i+1])
                distancia.append((vincenty(a, b).kilometers))
                if i+1 == len(latitud)-1:
                    a=b
                    b=(latitud[0], longitud[0])
                    distancia.append((vincenty(a, b).kilometers))

        for i in range(len(latitud)-1):
                a=(latitud[i]+0.30, longitud[i]+0.30)
                puntos.append(a)
                if i+1 == len(latitud)-1:
                    a=(latitud[i+1]+0.30, longitud[i+1]+0.30)
                    puntos.append(a)

        for i in range(len(ciudades)-1):
            a=(ciudades[i]+" a "+ciudades[i+1])
            ciudadesfinales.append(a)
            if i+1 == len(latitud)-1:
                    a=(ciudades[i+1]+" a "+ciudades[0])
                    ciudadesfinales.append(a)

        distancias=list(map(str,distancia))
        localizaciones=list(zip(latitud,longitud))

        for i in range(len(distancias)-1):
            a=(distancias[i]+" km ")
            distanciasfinales.append(a)
            if i+1 == len(latitud)-1:
                    a=(distancias[i+1]+" km ")
                    distanciasfinales.append(a)

        for i in range(len(distancias)-1):
            a=(ciudadesfinales[i]+" : "+ distanciasfinales [i])
            final.append(a)
            if i+1 == len(latitud)-1:
                    a=(ciudadesfinales[i+1]+" : "+ distanciasfinales [i+1])
                    final.append(a)
        print(final)
        print("Archivo Cargado Correctamente")
        opcion = 2
        if opcion == 2:

            for i in range(len(localizaciones)-1):
                ciudad1=
gmaps.directions_layer(localizaciones[i],localizaciones[i+1])
                m.add_layer(ciudad1)
                if i+1==len(localizaciones)-1 :
                    ciudad1=
gmaps.directions_layer(localizaciones[i+1],localizaciones[0])
                    m.add_layer(ciudad1)
            marcador = gmaps.marker_layer(localizaciones,label=ciudades)
            m.add_layer(marcador)

            symbol_layer = gmaps.symbol_layer(puntos,
info_box_content=final)
            m.add_layer(symbol_layer)
        return m

opcion1 = StringVar()
txtopcion = Entry(ventana,textvariable=opcion1).place(x=70,y=70)

boton = Button(ventana, text= "Cargar", command =
mostrar_mapa).place(x=10,y=90)


ventana.mainloop()

could you help me?

**Comment by pbugnion** [comment]
What is `ventana`?

**Comment by Nickl55** [comment]
ventana = Tk()
ventana.geometry("600x600")
ventana.title("Mini GPS")

labelopcion = Label(text = "Digite 1 para cargar el archivo", font =
("Comic Sans MS", 15)).place(x=10, y=10)
opcion1 = StringVar()
txtopcion = Entry(ventana,textvariable=opcion1).place(x=70,y=70)

boton = Button(ventana, text= "Cargar", command =
mostrar_mapa).place(x=10,y=90)


ventana.mainloop()

**Comment by pbugnion** [comment]
Are you expecting the map to appear inside the Tk window, or in the notebook?

**Comment by Nickl55** [comment]
At the moment it doesn't matter, but I think it would be better if the map
could appear in the window

**Comment by pbugnion** [comment]
I don't think you will be able to have a google map in a tkinter window, unless you can somehow embed html.

Here's a minimal example that demonstrates using a `Tk` window to show a map in the notebook:

```python
import tkinter
import gmaps
from IPython.display import display

app = tkinter.Tk()

def show_map():
    m = gmaps.Map()
    display(m)

button = tkinter.Button(app, text='show map', command=show_map).place(x=10, y=90)
    
app.mainloop()
```

<img width="1272" alt="screen shot 2017-05-14 at 21 04 35" src="https://cloud.githubusercontent.com/assets/1392879/26037371/467fa4b2-38e9-11e7-9b04-7ef44cdafed7.png">

That said, I think that you're going to have trouble going down that road: you're mixing two different GUI engines, and notebooks are probably not the right place from which to launch a `Tk` event loop.

I would recommend sticking entirely to jupyter widgets. By combining *jupyter-gmaps* with [default widgets](https://ipywidgets.readthedocs.io/en/latest/examples/Widget%20List.html), you should be able to build an app that lives entirely in the notebook.

**Comment by pbugnion** [comment]
Here's a minimal example showing the same thing, but with widgets:

```python
import gmaps
import ipywidgets
gmaps.configure(api_key="AIz...")

map_width = "700px"
map_height = "400px"

b = ipywidgets.Button(description='show map')

map_box = ipywidgets.HBox([]) # container for the map
map_box.layout.width = map_width
map_box.layout.height = map_height

def show_map(elem):
    m = gmaps.Map()
    m.layout.width = map_width
    m.layout.height = map_height
    map_box.children = [m] # append the map to the box
    
b.on_click(show_map)

ipywidgets.VBox([b, map_box])
```

<img width="1141" alt="screen shot 2017-05-14 at 21 34 15" src="https://cloud.githubusercontent.com/assets/1392879/26037552/2a3ca3aa-38ed-11e7-97a4-1d5dc166adb9.png">

**Comment by Nickl55** [comment]
Thanks Pascal.

The thing is i'm a college student, and teacher told us it must go with Tk
because it has to go with a Menu, so i just have to do what he says. I used
the first example with the tk window you sent me and it worked, i'm very
very thankful for that, now i have to find out how to implement DFS and
Dijkstra algorithms to that map... thats why i asked you how to change
color, but for now, i'm very happy i can progress with the next things.

Thank you.

**Comment by pbugnion** [comment]
Great -- best of luck.

Closing as resolved.
