### ISSUE TITLE
Is it possible to embed gmaps fig inside custom HTML or alongside other output

### ISSUE THREAD

**Issue by gatapia** [pbugnion/gmaps#155]
I am trying to display maps alongside some other content and this is not supported, for instance:
```
from IPython.display import display, HTML
...

data_frame_1 = ...
data_frame_2 = ...
fig = gmaps.figure()

display(data_frame_1)
display(fig)
display(data_frame_2)
```

However, the map displays at the top (in the code panel not the output panel) and then the other content below.

Ideally I would love the flexibility to do this:
```
...
display(HTML('<h1>DataFrame 1</h1> %s <h1>Map 1</h1>%s<h1>DF 2</h1>%s' % \
  (data_frame_1.to_html(), fig.to_html(), data_frame_2.to_html())))
```
Is this currently possible at all? If not, is the top option possible?

**Comment by pbugnion** [comment]
Yes, but you have to use the widgets machinery. *gmaps* is designed to compose with other [jupyter widgets](https://ipywidgets.readthedocs.io/en/latest/).

For instance:

```
import gmaps
gmaps.configure(api_key='...')

html_header = ipywidgets.HTML('<h1>Map 1</h1>')
map_ = gmaps.figure() # customise your map here
outer_box = ipywidgets.VBox([html_header, map_])
outer_box
```

**Comment by gatapia** [comment]
perfect. thanks
