### ISSUE TITLE
Having a single location can cause a "math domain error" in longitude_bounds

### ISSUE THREAD

**Issue by Stormbringer68** [pbugnion/gmaps#159]
I found an error while I was using an edge condition.  While I was plotting a lot of points, I only wanted to use 1 marker.  Most of the time, it would work correctly, but occasionally, I would get an error in bounds.py, in function “longitude_bounds” in the line:

```python 
standard_deviation = math.sqrt(-math.log(Rsq))
 ```

I found this happened only when what that function gets passed a single longitude and only a particular longitude (for now).  The case I found that causes an error is when `longitudes = [-87.6297]`.          ** - That is the longitude of Chicago, IL, USA
 
When that happens, `Rsq` is 1.0000000000000002 and it will throw `ValueError: math domain error`.  BTW, this is on  64-bit Windows 10 PC.

I will be submitting an update to longitude_bounds and a corresponding nose test to show the problem / show that it is fixed.

**Comment by pbugnion** [comment]
Thanks very much for submitting this and PR #160 !
