### ISSUE TITLE
polygon construction

### ISSUE THREAD

**Issue by tarunluthra** [pbugnion/gmaps#190]
does gmaps have the capability to draw polygons or polylines through its functionality yet? 
I have been looking to use that functionality to draw outlines. It seems to be a pretty important part for creating maps but it doesn't exist. Can anyone help in developing this capability?

**Comment by pbugnion** [comment]
Thanks for raising this.  I definitely agree that drawing polygons and markers is important.

I'm currently working on this in PR #183 .

**Comment by pbugnion** [comment]
This is now possible. See the [documentation](http://jupyter-gmaps.readthedocs.io/en/latest/tutorial.html#drawing-markers-lines-and-polygons) on drawing polygons for details.

**Comment by tarunluthra** [comment]
Hi,
Can this tool draw lines from a list of points?
Thanks,
Tarun

**Comment by pbugnion** [comment]
Please open a new issue, don't just comment on an existing issue. This makes is more discoverable for other people.
