### ISSUE TITLE
Pulling Info Box Content from File with Lat Longs

### ISSUE THREAD

**Issue by aapeebles** [pbugnion/gmaps#200]
hi! 
I've been trying to find an example of if you are use df.location (column of tuples) to pull in the location data, how to reference the df.city_name, or df.date, or df.zipcode in the info box - all pulling from one data frame.

If this is just an issue of me not knowing python well enough - please feel free to brush me off, but I haven't been able to find a dynamic example in the documentation.

**Comment by pbugnion** [comment]
`info_box_content` supports objects which are *like* a Python list (e.g. numpy arrays, lists, etc.). I presume you were trying to pass a Pandas series. While it makes sense to support pandas series, we don't at the moment, so you have to extract the numpy array underlying the series by calling `.values`.

Something like:

```
import gmaps
import gmaps.datasets

gmaps.configure(api_key="AIz...")

df = gmaps.datasets.load_dataset_as_df('starbucks_kfc_uk').sample(200)
# df is a dataframe with headers 'latitude', 'longitude' and 'chain_name'

fig = gmaps.figure()
marker_layer = gmaps.marker_layer(
    df[['latitude', 'longitude']],
    info_box_content=df['chain_name'].values
)
fig.add_layer(marker_layer)
fig # display the map
```

<img width="784" alt="screen shot 2017-11-09 at 07 17 01" src="https://user-images.githubusercontent.com/1392879/32592998-07aa81fa-c51e-11e7-8c3b-6be269012c37.png">

**Comment by pbugnion** [comment]
Closing in favour of #201. Feel free to reopen if you have issues.
