### ISSUE TITLE
Script error for "jupyter-gmaps" http://requirejs.org/docs/errors.html#scripterror

### ISSUE THREAD

**Issue by kychanbp** [pbugnion/gmaps#209]
I have installed using conda. 

Then I do this:

`import gmaps
import gmaps.datasets
gmaps.configure(api_key="")`

```
fig = gmaps.figure()
fig
```

And I received the following message:
```
Could not create model:
Model name	FigureModel
Model module	jupyter-gmaps
Model module version	0.7.0
Script error for "jupyter-gmaps" http://requirejs.org/docs/errors.html#scripterror

```

**Comment by pbugnion** [comment]
Thanks for raising this. It'd be great if you could answer the following:

 - Are you using Jupyter Notebook or JupyterLab?
 - What browser and OS are you using?
 - What is the output of `jupyter nbextension list`?
 - What does your browser console show when you first refresh your browser, then run this?

**Comment by rednaxel22** [comment]
I have the same error 

- I'm using Jupyter Notebooks 

- Im using Chrome in Windows

- This is the output of jupyter nbextension list

```
Known nbextensions:
  config dir: C:\Users\Michael\Anaconda3\etc\jupyter\nbconfig
    notebook section
      jupyter-js-widgets/extension enabled
      - Validating: ok
```

- The error says "Could not instantiate widget"

After some new test I got this error:
`Failed to display Jupyter Widget of type Figure.
If you're reading this message in the Jupyter Notebook or JupyterLab Notebook, it may mean that the widgets JavaScript is still loading. If this message persists, it likely means that the widgets JavaScript library is either not installed or not enabled. See the Jupyter Widgets Documentation for setup instructions.
If you're reading this message in another frontend (for example, a static rendering on GitHub or NBViewer), it may mean that your frontend doesn't currently support widgets.`

**Comment by pbugnion** [comment]
Thanks for reporting. The output of `jupyter nbextension list` is not correct. It should look like:

```
Known nbextensions:
  config dir: /Users/pascal/.jupyter/nbconfig
    notebook section
      jupyter-js-widgets/extension enabled
      - Validating: OK
      jupyter-gmaps/extension  enabled
      - Validating: OK
```

You're missing the `jupyter-gmaps` part. This typically happens when something went wrong running `$ jupyter nbextension enable --py --sys-prefix gmaps`. What is the output of this command?

**Comment by rednaxel22** [comment]
I executed the command you prompted and is working now, thank you very much.
