### ISSUE TITLE
Make gmaps work with JupyterLab

### ISSUE THREAD

**Issue by brickb** [pbugnion/gmaps#213]
Does gmaps work with Jupyterlab?  When I try a simple example, I get the error "Error displaying widget".  I have attached a screen shot of my console.    I also tried inserting a simply interactive widget to ensure that those are working.

Versions
jupyterlab: 0.31.1
jupyter notebook: 5.3.1
ipywidgets: 7.0.0

$ jupyter labextension list
JupyterLab v0.31.1
Known labextensions:
   app dir: /opt/jupyter/anaconda3/share/jupyter/lab
@jupyter-widgets/jupyterlab-manager
        @jupyter-widgets/jupyterlab-manager v0.33.0  enabled  OK
@jupyterlab/hub-extension
        @jupyterlab/hub-extension v0.8.0  enabled  OK
jupyter-matplotlib
        jupyter-matplotlib v0.3.0  enabled  OK

$ jupyter nbextension list
Known nbextensions:
  config dir: /opt/jupyter/anaconda3/etc/jupyter/nbconfig
    notebook section
      jupyter-js-widgets/extension  enabled
      - Validating: OK
      jupyter-matplotlib/extension  enabled
      - Validating: OK
      jupyter-gmaps/extension  enabled
      - Validating: OK

Any help would be appreciated.

![image](https://user-images.githubusercontent.com/35777053/35348020-d0b6afc0-0104-11e8-95e6-674a4b0d5fda.png)

**Comment by pbugnion** [comment]
> Does gmaps work with Jupyterlab

Not yet, no. This is on my list of things to do in the near-ish future, but PRs welcome in the meantime!

**Comment by pbugnion** [comment]
*jupyter-gmaps* 0.7.2-rc1 now supports JupyterLab, thanks to PR #218 :

```
pip install gmaps==0.7.2-rc1
jupyter lab build
```

I'll cut release 0.7.2 in the next few days.
