### ISSUE TITLE
Using With Tkinter

### ISSUE THREAD

**Issue by mustaphos** [pbugnion/gmaps#214]
Is there a way to plot a map in a GUI using Tkinter?

**Comment by pbugnion** [comment]
I know nothing about Tkinter, but, unless you can embed a webpage, or arbitrary HTML, then no.

**Comment by mustaphos** [comment]
i think you are showing the map as matplotlib object.
i am trying to embed a matplotlib object to tkinter but i get:
AttributeError: 'Figure' object has no attribute 'set_canvas'

**Comment by pbugnion** [comment]
> i think you are showing the map as matplotlib object.

No, jupyter-gmaps uses [jupyter widgets](https://github.com/jupyter-widgets/ipywidgets), not matplotlib plots.

> i am trying to embed a matplotlib object to tkinter but i get: AttributeError: 'Figure' object has no attribute 'set_canvas'

I suggest asking for help on the matplotlib mailing list, or in the repo. This is very far from my area of expertise.

**Comment by pbugnion** [comment]
Closing this issue as I don't think tkinter is a backend that we want to support (or even can support). Feel free to reopen if you think otherwise.
