### ISSUE TITLE
Heatmap does not show

### ISSUE THREAD

**Issue by anderl80** [pbugnion/gmaps#219]
Version: '0.7.2'

Map shows, but the heatmap does not.

```
fig = gmaps.figure()
fig.add_layer(gmaps.heatmap_layer(
    [(48.1364545, 11.53440083),
     (48.13651917, 11.53441683),
     (48.13657283, 11.53440517),
     (48.13661917, 11.53439917),
     (48.136695, 11.534386),
     (48.13673717, 11.53438433),
     (48.136849, 11.53442983),
     (48.13691783, 11.53443767),
     (48.13704817, 11.5344605),
     (48.13718383, 11.53447267),
     (48.13723717, 11.53447883)]))
fig
```

If i try to save the figure with the png button, a warning shows up:

![image](https://user-images.githubusercontent.com/23196828/36719574-b17c07d4-1ba5-11e8-8022-94a5e0dfe9c6.png)

Tested also the acled_africa_by_year example from the guide with no result.

**Comment by pbugnion** [comment]
That's strange -- your example works perfectly here (I've redacted the API key):

<img width="890" alt="screen shot 2018-02-27 at 19 45 41" src="https://user-images.githubusercontent.com/1392879/36751019-e05e78c4-1bf6-11e8-9b12-bc849dfe1303.png">

What browser are you using?

**Comment by anderl80** [comment]
I kind of had problems with the transit layer but now, problem is completely gone. Probabely a proper kernel restart did the trick. Sorry for inconvenience, thx for support!
