### ISSUE TITLE
Force the figure to satellite view

### ISSUE THREAD

**Issue by valschmidt** [pbugnion/gmaps#222]
This may be a feature request, or maybe it is a documentation request if it is already possible and I have simply been unable to sort out how. 

In any event, it would be useful to be able to pass an argument to "figure()" to force the map into satellite view (e.g satellite images vs cartographic maps). 

In the examples some maps are shown in cartographic view and others in satellite view, with no distinction in the example code. I suspect the change has been made manually by clicking in the resulting plot. It would be useful to be able to specify this explicitly, programmatically.

**Comment by pbugnion** [comment]
Thanks for raising this!

This is not currently possible. PRs welcome!

For anyone wanting to implement this, I suggest adding a `map_type` traitlet to `Map` and an argument to the `figure` factory. The `map_type` traitlet would take values `roadmap`, `satellite`, `hybrid` or `terrain` and pass these through to the frontend.

See [this](https://developers.google.com/maps/documentation/javascript/maptypes) page for the frontend documentation.

**Comment by pbugnion** [comment]
Closed in PR #232. This will be available in gmaps 0.7.4 (now released).
