### ISSUE TITLE
Allow user to draw on map in browser / produce list of coordinates

### ISSUE THREAD

**Issue by acresnick** [pbugnion/gmaps#223]
Hello,

This is a great package! It's more comprehensively met my needs than any other python/google maps interface.

One additional feature that could be very useful: the ability to export an .html file, send it to someone else who can then open it up in their browser, draw on it, save it, and send it back. Is this possible?

Currently when I use a drawing layer:

1) I cannot export to .png
2) When I export to .html and open in browser, I cannot add markers, polygons, or lines -- the drawing pallet is there, but the markers don't show up on click.

In both cases when I try to save/export I get the following:
"Cannot download layer: DrawingLayerView. Remove these layers to export the map."

Thanks!

**Comment by pbugnion** [comment]
Hi,

Thanks very much for the feedback.

Exporting maps with a drawing layer to PNG should just work -- I'll open a separate issue. Note that the user won't be able to interact with the PNG, so presumably that won't solve your issue?

With the package as it currently stands, exporting an interactive version of the drawing layer to HTML is not possible -- user interactions in the drawing layer rely on the maps being backed by a Jupyter server. I agree that it would be nice to move that into the browser client so it still works when exported to HTML.

If I were in your position, I would either:

- host a notebook server on a cloud provider (e.g. Amazon EC2) and invite *trusted* users to draw on that directly. If you do that, you need to make sure you secure access to your notebook.
- with untrused users, use very experimental widget dashboarding features like [this](https://github.com/pbugnion/ipywidgets_server) or [this](https://github.com/maartenbreddels/flask-ipywidgets) to host a dashboard on a cloud provider (e.g. Amazon EC2).
- use something like [binder](https://mybinder.org/) to provide a throw-away notebook environment backed by a GitHub repository.
- use the free trial period of a platform for hosting notebooks -- [Google Colaboratory](https://colab.research.google.com/notebooks/welcome.ipynb) (I have no experience with that, so no promises) or [SherlockML](https://sherlockml.com/) (full disclosure: this is what I work on for my day job).

**Comment by acresnick** [comment]
Thanks much for the thorough feedback!

**Comment by pbugnion** [comment]
Closing this in favour of issues #224 and #226. Feel free to carry on discussing this here, or in the new issues, or re-opening if you think issues 224 and 226 don't address everything.
