### ISSUE TITLE
Non-dissipating GeoJSON features?

### ISSUE THREAD

**Issue by sid-kap** [pbugnion/gmaps#228]
I'm plotting a LineString using gmaps.geojson_layer, and I noticed that as I zoom in and out, the stroke weight of the line changes.
Is there a way to make this stay the same regardless of zoom? My guess was `layer.dissipating = False` would do the job, but that did not work.

**Comment by pbugnion** [comment]
> the stroke weight of the line changes.

I can't really reproduce that. The stroke weight should just remain the same number of screen pixels.

I've been testing on this minimal example:

```python
import gmaps
import geojson
gmaps.configure(api_key='...')

t = geojson.LineString([(8.919, 44.4074), (8.923, 44.4075)])
c = geojson.Feature(geometry=t)
coll = geojson.FeatureCollection([c])
l = gmaps.geojson_layer(coll, stroke_weight=2.0)
fig = gmaps.figure()
fig.add_layer(l)
fig
```

Here's a [video](https://www.dropbox.com/s/rqsen4qrsig9r0y/demo-weight.mov?dl=0) of zooming in and out (let me know if you can't open the file; note that the link will expire on the 1st May). How does that compare to what you see?

**Comment by sid-kap** [comment]
Sorry if I was unclear—I'm getting the same behavior as you. I was looking for a way to have the width to stay the same in terms of map scale, rather than pixel scale.

The context is that I'm displaying a lot of bus routes, and if I zoom out, they all become really thick and overlap with each other. I want them to be wide when zoomed in but thin while zoomed out.

**Comment by sid-kap** [comment]
That looks like it might work for me. Thanks!!
