### ISSUE TITLE
Subplots support

### ISSUE THREAD

**Issue by dorcoh** [pbugnion/gmaps#234]
Hi, Is there an option to output multiple plots, as in matplotlib.pyplot.subplot (on Jupyter)?
I'd be grateful for any other workaround to plot multiple maps besides doing it manually

Many thanks

**Comment by pbugnion** [comment]
Thanks for raising this!

jupyter-gmaps are a [Jupyter widget](https://ipywidgets.readthedocs.io/en/latest/) -- you can use those to create layouts. In particular, the `HBox` and `VBox` class let you stack maps vertically or horizontally:

```py
import gmaps
import ipywidgets as widgets
gmaps.configure(api_key="AIza...5Ys")

lhs = gmaps.figure(layout={'width': '45%', 'margin': 'auto'})
rhs = gmaps.figure(center=(40.75, -74.00), zoom_level=12, layout={'width': '45%', 'margin': 'auto'})
title = widgets.HTML('<h3>My great maps!</h3>')
widgets.VBox([
    title,
    widgets.HBox([lhs, rhs], layout={'width': '100%'})
])
```

<img width="883" alt="screen shot 2018-04-04 at 19 05 44" src="https://user-images.githubusercontent.com/1392879/38325561-3c1c7b74-383b-11e8-80ad-0830e04122f8.png">

Notice that I use `width: 45%` to make the maps occupy 45% of their parent container. The parent container (the `HBox`) is set to occupy `100%` of its container, the Jupyter output cell. I also give the maps the `margin: auto` property so your browser distributes whitespace (the remaining 10% horizontal space) equally around the maps.

For more information on how layout, `HBox` and `VBox` interact, I suggest [this](https://ipywidgets.readthedocs.io/en/latest/examples/Widget%20Styling.html) page in the ipywidgets documentation.

**Comment by dorcoh** [comment]
Many thanks for your reply, I will check it out!

**Comment by pbugnion** [comment]
Closing this as I think the right place to handle complex layouts with multiple maps should be through ipywidgets, not jupyter-gmaps.

Feel free to carry on commenting on this if you need help with layouts, or reopening if you think there's more we should do in gmaps itself.
