### ISSUE TITLE
Map not showing on notebook

### ISSUE THREAD

**Issue by orenp85** [pbugnion/gmaps#246]
Hi,

I tried using the code for the San Francisco taxi in my notebook, but the map does not appear on my notebook. Not getting any error messages. Any idea what the problem might be?

Thanks,
Oren

**Comment by DieterDePaepe** [comment]
I have the same issue. When following the examples in the readme, the `fig` command simply prints `Figure(layout=FigureLayout(height='420px'))` in the notebook, it does not display the figure.

Installed using:
`conda install -c conda-forge gmaps`

Versions:
```
alabaster (0.7.10)
anaconda-client (1.6.3)
anaconda-navigator (1.6.2)
anaconda-project (0.6.0)
asn1crypto (0.22.0)
astroid (1.4.9)
astropy (1.3.2)
Babel (2.4.0)
backports.shutil-get-terminal-size (1.0.0)
beautifulsoup4 (4.6.0)
bitarray (0.8.1)
blaze (0.10.1)
bleach (1.5.0)
bokeh (0.12.5)
boto (2.46.1)
Bottleneck (1.2.1)
cffi (1.10.0)
chardet (3.0.3)
click (6.7)
cloudpickle (0.2.2)
clyent (1.2.2)
colorama (0.3.9)
comtypes (1.1.2)
conda (4.5.4)
contextlib2 (0.5.5)
cryptography (1.8.1)
cycler (0.10.0)
Cython (0.25.2)
cytoolz (0.8.2)
dask (0.14.3)
datashape (0.5.4)
decorator (4.0.11)
distributed (1.16.3)
docutils (0.13.1)
entrypoints (0.2.2)
et-xmlfile (1.0.1)
fastcache (1.0.2)
Flask (0.12.2)
Flask-Cors (3.0.2)
geojson (2.3.0)
gevent (1.2.1)
gmaps (0.8.0)
gmplot (1.2.0)
greenlet (0.4.12)
h5py (2.7.0)
HeapDict (1.0.0)
html5lib (0.999)
httpie (0.9.9)
idna (2.5)
imagesize (0.7.1)
ipykernel (4.6.1)
ipython (5.3.0)
ipython-genutils (0.2.0)
ipywidgets (7.2.1)
isodate (0.5.4)
isort (4.2.5)
itsdangerous (0.24)
jdcal (1.3)
jedi (0.10.2)
Jinja2 (2.9.6)
jsonschema (2.6.0)
jupyter (1.0.0)
jupyter-client (5.0.1)
jupyter-console (5.1.0)
jupyter-core (4.3.0)
lazy-object-proxy (1.2.2)
llvmlite (0.18.0)
locket (0.2.0)
lxml (3.7.3)
MarkupSafe (0.23)
matplotlib (2.0.2)
menuinst (1.4.7)
mistune (0.7.4)
mpmath (0.19)
msgpack-python (0.4.8)
multipledispatch (0.4.9)
navigator-updater (0.1.0)
nbconvert (5.1.1)
nbformat (4.3.0)
networkx (1.11)
nltk (3.2.3)
nose (1.3.7)
notebook (5.0.0)
numba (0.33.0)
numexpr (2.6.2)
numpy (1.13.1)
numpydoc (0.6.0)
odo (0.5.0)
olefile (0.44)
openpyxl (2.4.7)
packaging (16.8)
pandas (0.23.0)
pandocfilters (1.4.1)
partd (0.3.8)
path.py (10.3.1)
pathlib2 (2.2.1)
patsy (0.4.1)
pep8 (1.7.0)
pickleshare (0.7.4)
Pillow (5.0.0)
pip (9.0.1)
ply (3.10)
prompt-toolkit (1.0.14)
psutil (5.2.2)
py (1.4.33)
pycosat (0.6.3)
pycparser (2.17)
pycrypto (2.6.1)
pycurl (7.43.0.2)
pydash (4.1.0)
pyFFTW (0.10.5.dev0+d45d7fe)
pyflakes (1.5.0)
Pygments (2.2.0)
pylint (1.6.4)
pyodbc (4.0.16)
pyOpenSSL (17.0.0)
pyparsing (2.1.4)
pytest (3.0.7)
pytest-runner (2.11.1)
python-dateutil (2.6.0)
pytz (2017.2)
PyWavelets (0.5.2)
pywin32 (220)
PyYAML (3.12)
pyzmq (16.0.2)
QtAwesome (0.4.4)
qtconsole (4.3.0)
QtPy (1.2.1)
rdflib (4.2.2)
recordclass (0.4.3)
requests (2.14.2)
rope-py3k (0.9.4.post1)
scikit-image (0.13.0)
scikit-learn (0.19.0)
scipy (0.19.1)
seaborn (0.7.1)
setuptools (27.2.0)
simplegeneric (0.8.1)
singledispatch (3.4.0.3)
six (1.10.0)
snowballstemmer (1.2.1)
sortedcollections (0.5.3)
sortedcontainers (1.5.7)
sphinx (1.5.6)
spyder (3.1.4)
SQLAlchemy (1.1.9)
statsmodels (0.8.0)
sympy (1.0)
tables (3.2.2)
tblib (1.3.2)
testpath (0.3)
toolz (0.8.2)
tornado (4.5.1)
traitlets (4.3.2)
unicodecsv (0.14.1)
wcwidth (0.1.7)
Werkzeug (0.12.2)
wheel (0.29.0)
widgetsnbextension (3.2.1)
win-unicode-console (0.5)
wrapt (1.10.10)
xlrd (1.0.0)
XlsxWriter (0.9.6)
xlwings (0.10.4)
xlwt (1.2.0)
yellowbrick (0.6)
zict (0.1.2)
```

**Comment by pbugnion** [comment]
Thanks -- to help diagnose this further:

1. Do other widgets work? The following snippet should display a slider:

```
import ipywidgets as widgets
widgets.IntSlider()
```

2. What's the output of:

```
jupyter nbextension list
```

**Comment by DieterDePaepe** [comment]
Initially, the widget did not display, but after restarting the kernel, it did. I tried the non-working example again, and now it works, so I no longer suffer from this issue. I have been messing with some other map plugins in the meanwhile, so not sure what caused the original problem.

For reference, this was output of `jupyter nbextension list`

> Known nbextensions:
>   config dir: C:\Users\didpaepe\Anaconda3\etc\jupyter\nbconfig
>     notebook section
>       jupyter-js-widgets/extension enabled
>       - Validating: ok
>       jupyter-gmaps/extension enabled
>       - Validating: ok

**Comment by evadeflow** [comment]
I'm having a similar problem. Restarting the kernel doesn't appear to help. I _think_ I have the required extensions enabled:

```
$ jupyter nbextension list
Known nbextensions:
  config dir: /home/dwolfe/.virtualenvs/jupyter/etc/jupyter/nbconfig
    notebook section
      jupyter-js-widgets/extension  enabled 
      - Validating: OK
      jupyter-gmaps/extension  enabled 
      - Validating: OK
```

But the map doesn't display. I _do_ see a large blank area where the map should be, though, and a download icon:

![image](https://user-images.githubusercontent.com/195848/43286638-ae8d94d2-90f0-11e8-8d4e-be741faa1062.png)

When I click the download link, the `map.png` file it downloads is blank.

It's quite possible (likely, even) that this is due to user error on my part. I've never used the Google Maps API before, so I should probably try to determine what the "Hello, World" equivalent for that API is and confirm whether my credentials work.

Another complicating factor is that I'm viewing the notebook in Firefox, inside an Ubuntu 16.04 VM running under VirtualBox for Windows 7 Enterprise. Maybe it's trying to use gl extensions (or something) that don't work in this scenario?

**Comment by evadeflow** [comment]
Oops—yes, this was user error. :blush:  What I didn't mention is: I was attempting to run behind a corporate HTTP proxy. Normally, it Just Works™, but I had disabled the proxy to do some testing on another project and forgot to re-enable it.

After re-enabling the proxy, everything seems to be working fine. (I'll make a note of this in issue #250 as well...)

**Comment by jwhendy** [comment]
For any others using this the first time and stumbling here or #277, use [these instructions](https://jupyter-gmaps.readthedocs.io/en/latest/install.html). I was following a gmaps tutorial which mentioned none of that content, and in the troubleshooting above installing `jupyterlab-manager` and enabling `widgetsnbextension` aren't mentioned. That was the answer for me.

**Comment by jjjdewan** [comment]
Here is a code I tested and it did not display any map. Any idea what could happen?

import gmaps
import gmaps.datasets

gmaps.configure(api_key='my-API-key') # I used my API here 
fig = gmaps.figure()
fig

**Comment by quiquealonso8** [comment]
hey, did u finally issue the problem? I have exactly the same problem

**Comment by quiquealonso8** [comment]
solve*

**Comment by rllemos** [comment]
> Thanks -- to help diagnose this further:
> 
> 1. Do other widgets work? The following snippet should display a slider:
> 
> ```
> import ipywidgets as widgets
> widgets.IntSlider()
> ```
> 
> 2. What's the output of:
> 
> ```
> jupyter nbextension list
> ```

Hi, my jupyter nbextension list is showing as 
known nbextension: 
simply blank
Also when I ran the 
> import ipywidgets as widgets
> widgets.IntSlider()
I get IntSlider(value=0)

I keep getting the same error : Figure(layout=FigureLayout(height='420px'))

please I appreciate any help

**Comment by dheeraj09D** [comment]
I am having the same problem but
1) I am getting the slider on display
2) jupyter-js-widgets/extension enabled
      - Validating: ok
      jupyter-gmaps/extension enabled
      - Validating: ok  
     getting this for nbextension list.

Any leads will be appreciated. Thanks.
