### ISSUE TITLE
Development version install failed

### ISSUE THREAD

**Issue by Corccaroli** [pbugnion/gmaps#255]
It seems there is a missing 'build' script in ./js/package.json

npm log file is as follows:

> 0 info it worked if it ends with ok
> 1 verbose cli [ '/usr/local/bin/node', '/usr/local/bin/npm', 'run', 'build' ]
> 2 info using npm@6.1.0
> 3 info using node@v10.4.1
> 4 verbose stack Error: missing script: build
> 4 verbose stack     at run (/usr/local/lib/node_modules/npm/lib/run-script.js:151:19)
> 4 verbose stack     at /usr/local/lib/node_modules/npm/lib/run-script.js:61:5
> 4 verbose stack     at /usr/local/lib/node_modules/npm/node_modules/read-package-json/read-json.js:115:5
> 4 verbose stack     at /usr/local/lib/node_modules/npm/node_modules/read-package-json/read-json.js:418:5
> 4 verbose stack     at checkBinReferences_ (/usr/local/lib/node_modules/npm/node_modules/read-package-json/read-json.js:373:45)
> 4 verbose stack     at final (/usr/local/lib/node_modules/npm/node_modules/read-package-json/read-json.js:416:3)
> 4 verbose stack     at then (/usr/local/lib/node_modules/npm/node_modules/read-package-json/read-json.js:160:5)
> 4 verbose stack     at /usr/local/lib/node_modules/npm/node_modules/read-package-json/read-json.js:280:12
> 4 verbose stack     at /usr/local/lib/node_modules/npm/node_modules/graceful-fs/graceful-fs.js:78:16
> 4 verbose stack     at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:442:3)
> 5 verbose cwd /home/fish/Documents/GMAPS/gmaps/js
> 6 verbose Linux 4.13.0-45-generic
> 7 verbose argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "build"
> 8 verbose node v10.4.1
> 9 verbose npm  v6.1.0
> 10 error missing script: build
> 11 verbose exit [ 1, true ]

**Comment by pbugnion** [comment]
Good catch, thanks! This was left over from when we changed how the JavaScript gets built.

Fixed by PR #256. Feel free to reopen this if it still isn't working for you.
