### ISSUE TITLE
Adding Widgets into google maps data tables

### ISSUE THREAD

**Issue by agiles37** [pbugnion/gmaps#264]
Hi, I am a very basic beginning on google maps, i have added a number of markers into a custom map to highlight where specific care homes for the elderly are. there is a body that inspects these and they provide widgets that can be added to the homes webpage, i would like to add this widget into my maps for each home so its live in terms of its current rating. is there a way do do this via the data tables or will i need additional software? thanks

**Comment by pbugnion** [comment]
Thanks for raising this.

I'm not sure I understand what you mean. Could you provide some examples or screenshots of what you're trying to do?

> is there a way do do this via the data tables

What is 'the data tables'? Can you provide a link?

**Comment by pbugnion** [comment]
I'm a bit confused -- you just posted an HTML `<script />` tag.

Do you mean -- when someone clicks on a marker, you want to show a popup showing some information?

**Comment by agiles37** [comment]
is that not code for a widget as that is what the cqc website gave me, could i use this?

**Comment by pbugnion** [comment]
This repository is for interacting with Google Maps in a Jupyter notebook from Python -- that code is JavaScript. How were you thinking of using it?

**Comment by pbugnion** [comment]
Closing this issue as it's unclear what the problem is. Feel free to reopen.
