### ISSUE TITLE
Size of the dataset and time loading

### ISSUE THREAD

**Issue by aspence1392** [pbugnion/gmaps#266]
Is there a limitation on the size of the dataset that one can use? I have got a fairly large dataset (about 500k) points and it seems to get stuck when I try to do a scatterplot.

**Comment by pbugnion** [comment]
Thanks for raising this.

Google maps doesn't really support drawing more than a few thousand points. For higher-dimensional datasets, it probably makes more sense to use a heatmap. Marker clustering (issue #137) would also resolve this, but is not implemented yet (PRs welcome!).

**Comment by pbugnion** [comment]
Closing this, since we already have issue #137 for marker clustering and a [reference to dataset size limitations](https://jupyter-gmaps.readthedocs.io/en/latest/tutorial.html#dataset-size-limitations) in the docs.
