### ISSUE TITLE
map fig url

### ISSUE THREAD

**Issue by eloiup** [pbugnion/gmaps#283]
is there a url of the map/plot generated so I can pass it to a third party to view/interact?

tried one of the basic examples, cldnt find any property on "fig" that wld be an url

**Comment by eloiup** [comment]
nvm

found it; https://jupyter-gmaps.readthedocs.io/en/stable/export.html

**Comment by pbugnion** [comment]
Yes! I would export to HTML and then either serve that directly or embed it in a iframe.

Bear in mind that some of the functionality won't work when exported: functionality that requires an active Python kernel won't work:
- the drawing layer
- updates to layers after they are drawn

If these are important, you are probably best off serving the notebook using, e.g. [voila](https://github.com/QuantStack/voila) and embedding that.
