### ISSUE TITLE
gmaps does not show on Spyder

### ISSUE THREAD

**Issue by jsong005** [pbugnion/gmaps#296]
I am trying out a heatmap example:

`import gmaps`
`import gmaps.datasets
`
`gmaps.configure(api_key="...")`
`earthquake_df = gmaps.datasets.load_dataset_as_df( 'earthquakes' ) `
`locations = earthquake_df[[ 'latitude' , 'longitude' ]] `
`weights = earthquake_df[ 'magnitude' ] `
`fig = gmaps.figure() `
`fig.add_layer(gmaps.heatmap_layer(locations, weights=weights)) `
`fig`

However, the map does not show up and I get the following output instead:
`Figure(layout=FigureLayout(height='420px'))`

I am using Spyder(Python 3.7)

**Comment by pbugnion** [comment]
> I am using Spyder(Python 3.7)

Do you mean that you are using notebooks within Spyder? (I don't know much about Spyder)

**Comment by jsong005** [comment]
> Do you mean that you are using notebooks within Spyder? (I don't know much about Spyder)

I am using the Spyder IDE

**Comment by pbugnion** [comment]
This is a plugin for displaying Google Maps in Jupyter notebooks. I don't know what level of support jupyter-widgets have in Spyder, but I expect none?

You may be able to get some mileage from exporting to html and viewing that file in a browser. Follow [this](https://jupyter-gmaps.readthedocs.io/en/latest/export.html#exporting-to-html) documentation.

**Comment by pbugnion** [comment]
Closing this as out of scope. Feel free to re-open if you think I'm mistaken.
