### ISSUE TITLE
heatmap and large dataset

### ISSUE THREAD

**Issue by rthen** [pbugnion/gmaps#297]
Hi!

I wasn't sure if this was an issue or expected behavior but when plotting a large dataset of coordinates(424 rows worth of coordinates), you can see the red area when zoomed out. However, as you zoom in, the red color disappears and the map doesn't show any of the coordinates in the heat map. Please view attached screenshot.

![zoom_out](https://user-images.githubusercontent.com/39934293/54329335-a2a51300-45e7-11e9-8ec0-e5782972c8d2.png)
![zoom_in](https://user-images.githubusercontent.com/39934293/54329336-a33da980-45e7-11e9-97be-d7eb09e754ff.png)

Thank you

**Comment by pbugnion** [comment]
Thanks for raising this. 

Have you looked at the [Preventing dissipation on zoom](https://jupyter-gmaps.readthedocs.io/en/latest/tutorial.html#preventing-dissipation-on-zoom) section in the documentation?

**Comment by rthen** [comment]
Hey Pascal!

Thank you for the quick response. Changing the values did fixed my issue. Would it be possible to add that link/instrunctions to the README file? I think people might find that useful in the future. 

Thank you
