### ISSUE TITLE
Info box content style

### ISSUE THREAD

**Issue by lrondi** [pbugnion/gmaps#302]
Hi!

Is it possible to add style to the content on the info box? Like new lines, bullets, bold, italics, etc.

Thank you very much!

**Comment by lrondi** [comment]
Found the tutorial.

**Comment by pbugnion** [comment]
Great! 

For anybody else reading this, there's information [here](https://jupyter-gmaps.readthedocs.io/en/latest/tutorial.html#markers-and-symbols).

You can just embed HTML in the info box, so writing something like:

```html
<b>this is bold</b>
<i>this is italic</i>
```

should just work.
