### ISSUE TITLE
Directions layer not drawing routes line in google colab 

### ISSUE THREAD

**Issue by ppcfish** [pbugnion/gmaps#338]
i used google colab and display map like that:

import IPython
IPython.display.HTML(filename='export.html')

gmaps.drawing_layer is work well, 
but gmaps.directions_layer  only show map / Marker ,  not show routes line

did any no know why? many thank

![1](https://user-images.githubusercontent.com/10181466/80335938-646cc080-8888-11ea-9cef-d47aa0980585.JPG)

**Comment by gabriel-jones** [comment]
Did you find a fix for this?

**Comment by parhampr** [comment]
Did you find a fix for this yet?

**Comment by ja-lgh** [comment]
I think its because After that red s after the word false

**Comment by ppcfish** [comment]
> Did you find a fix for this yet?

no，i give up. maybe it only work on jupyter_notebook
