### ISSUE TITLE
import Error from IPython.html import widgets

### ISSUE THREAD

**Issue by icam0** [pbugnion/gmaps#43]
When I try to type import gmaps into the terminal it gives me the following error:

----> 2 from IPython.html import widgets
      3 from IPython.utils.traitlets import List, Unicode, Bool
      4 
      5 import ipy23_compat

ImportError: cannot import name widgets 

I'm using python 64 bit 2.7 on canopy gmaps version 0.1.6 and python version 2.4.1

**Comment by pbugnion** [comment]
Do you mean IPython version 2.4.1?

I just tried reproducing this with IPython 2.4.1, but gmaps imports correctly. What happens when you type 

    from IPython.html import widgets

in an IPython notebook?

**Comment by pbugnion** [comment]
Closed as not reproduced
