### ISSUE TITLE
No module named 'loader' at pip install

### ISSUE THREAD

**Issue by chanansh** [pbugnion/gmaps#47]
C:\Users\XXX\AppData\Local\Continuum\Anaconda3>pip install gmaps
Collecting gmaps
  Downloading gmaps-0.1.6.tar.gz (98kB)
    100% |################################| 102kB 1.5MB/s
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 20, in <module>
      File "C:\Users\XXX\AppData\Local\Temp\pip-build-m3s6zj_3\gmaps\setup.py", line 7, in <module>
        import gmaps
      File "C:\Users\XXX\AppData\Local\Temp\pip-build-m3s6zj_3\gmaps\gmaps\__init__.py", line 2, in <module>
        from loader import init
    ImportError: No module named 'loader'

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in C:\Users\XXX\AppData\Local\Temp\pip-build-m3s6zj_3\gmaps

**Comment by pbugnion** [comment]
Are you running this using Python 3?

**Comment by chanansh** [comment]
Yes

**Comment by pbugnion** [comment]
There is no Python 3 support at the moment, though adding it in would be quite easy. Pull requests welcome.

If you're using Python 3, it probably makes sense to always state that explicitly in bug reports -- I'd have been pretty flummoxed without the `Anaconda3` in your prompt.
