### ISSUE TITLE
Save created map as an image

### ISSUE THREAD

**Issue by stellasia** [pbugnion/gmaps#50]
It would be wonderful to be able to save the displayed map as an image (png or whatever). Is it already feasible with the current version? If not do you think it can be added?

**Comment by pbugnion** [comment]
As far as I know, you cannot save Google maps as pictures. I therefore can't think of a good way of adding this functionality. If you (or anyone else) has bright ideas, I would definitely be open to hearing them, though.

At the moment, I expect your best bet is to take a screenshot.

**Comment by pbugnion** [comment]
Closing this as there is no scope for resolution at this stage.

**Comment by stellasia** [comment]
Hi, I don't know enough yet to have bright idea I think :) But thank you for the answer, if I have any clue, I'll let you know.
