### ISSUE TITLE
Map doesn't display in Exported HTML

### ISSUE THREAD

**Issue by AlexNisnevich** [pbugnion/gmaps#51]
When I export an ipython notebook as HTML, the map doesn't display. I'm wondering if there's any simple workaround for this.

**Comment by pbugnion** [comment]
Yes, it would definitely be cool to be able to do that (I definitely need something like that just to write documentation for gmaps). Annoyingly, I don't think this is trivial: the IPython interactive widget machinery relies entirely on the presence of a kernel behind it. The widgets have no independent existence, they are more of a special view onto data that resides in the kernel.

Hacking something together would definitely still be possible, but not particularly easy or elegant. It's definitely on my list of things to do, but I doubt I will be able to make significant headway in the near future. Happy to accept / review / guide pull requests, though, obviously.
