### ISSUE TITLE
question big dataset

### ISSUE THREAD

**Issue by geraldstanje** [pbugnion/gmaps#56]
Hi,

first of all great lib.

is gmaps able to handle 200k geo points (lat/long)? How can you update the heatmap on the fly and add new datapoints?

Thanks

**Comment by pbugnion** [comment]
In [this](http://jupyter-gmaps.readthedocs.io/en/latest/gmaps.html#heatmaps) example, we plot a dataset with 110K points. In practice, I've noticed issues with the initial rendering above 500K points.
