### ISSUE TITLE
Jupyter unrecognized flag

### ISSUE THREAD

**Issue by kimling** [pbugnion/gmaps#59]
When enabling widget extension for Jupyter I get:
`
[EnableNBExtensionApp] CRITICAL | Bad config encountered during initialization:
[EnableNBExtensionApp] CRITICAL | Unrecognized flag: '--py'
`
I tried to look around on Jupyter shell commands but couldn't find reference to '--py' on help pages
Am I missing some package etc?

**Comment by pbugnion** [comment]
You don't need additional packages beyond Jupyter and ipywidgets. This probably comes from a version incompatibility. Which version of Jupyter and ipywidgets are you using? You can find out with 

```
pip list | grep jupyter
```

and...

```
pip list | grep ipywidgets
```

It would be useful if you pasted the output of both commands.

**Comment by pbugnion** [comment]
Closing as not reproduced.
