### ISSUE TITLE
Leaflet support?

### ISSUE THREAD

**Issue by karussell** [pbugnion/gmaps#69]
Do you plan to support a more open solution like [leaflet](http://leafletjs.com/) or openlayers or do you know alternatives?

What I found was only this project: https://github.com/SciTools/cartopy

**Edit**: found one: https://github.com/python-visualization/folium

**Comment by pbugnion** [comment]
[ipyleaflet](https://github.com/ellisonbg/ipyleaflet) does the same thing as gmaps, but for leaflet. Folium is different inasmuch as it doesn't try and integrate with Jupyter notebooks, AFAIK.
