### ISSUE TITLE
Changing heatmap properties

### ISSUE THREAD

**Issue by VXeonix** [pbugnion/gmaps#73]
Hey everyone,

I was wondering what the best way would be to go about changing the heatmap properties.
I tried using [the google heatmap reference](https://developers.google.com/maps/documentation/javascript/reference#HeatmapLayerOptions) but didn't get very far.

I am sorry if this is a dumb question, I'm not very experienced.

Thanks in advance!

**Comment by pbugnion** [comment]
At the moment, you can only set the `maxIntensity` and `radius` properties. For instance:

```python
import gmaps
import gmaps.datasets
gmaps.configure("AI...")

m = gmaps.Map()
heatmap_layer = gmaps.Heatmap(data=data)
heatmap_layer.max_intensity = 100
heatmap_layer.point_radius = 5
m.add_layer(heatmap_layer)
m
```

Pull requests for additional properties, eg `dissipating`, `gradient` and `opacity` are welcome! `dissipating` and `opacity` should be fairly easy, `gradient` may require a bit more thought when designing the interface.

**Comment by VXeonix** [comment]
Thanks for the quick reply!
I should've read [the jupyter gmaps documentation](http://jupyter-gmaps.readthedocs.io/en/latest/) instead, I now see that it also explains this.


I won't be able to make a pull request myself though ^^

**Comment by pbugnion** [comment]
Which options do you need? No promises on implementing anything, but it would inform how we do further development.

**Comment by VXeonix** [comment]
I think the `dissipating` property would be most useful, it allows you to more quickly see real hotspots.

**Comment by pbugnion** [comment]
Thanks. We'll take this into account. 

Closing in favour of PR #74.
