### ISSUE TITLE
GMaps does not show up

### ISSUE THREAD

**Issue by quang-ha** [pbugnion/gmaps#79]
I have tried running the simple example:

```
import gmaps
import gmaps.datasets

gmaps.configure(api_key="AIzaSyDOESksOPLhqEw...")

m = gmaps.Map()
m
```

but nothing shows up - the kernel keeps running forever. In the terminal it says:

```
(404 GET /static/jupyter-gmaps.js?v=20160823123004 (127.0.0.1) 9.95ms referer=http://localhost:8888/notebooks/test-gmaps.ipynb)
```

**Comment by pbugnion** [comment]
This looks like an installation problem -- the javascript part of the module hasn't been correctly put into a directory where the notebook can access it. What happens when you type:

```
jupyter nbextension enable --py gmaps
```

**Comment by quang-ha** [comment]
I got this:

```
Enabling notebook extension jupyter-gmaps/extension...
      - Validating: OK
```

so it should work, but it doesn't...

**Comment by quang-ha** [comment]
hang on it works after I switch my computer on and off again (no joke!)

**Comment by pbugnion** [comment]
That's great!

I'm not sure when JS extensions are picked up by the Jupyter notebook server, but I suspect that it's only when the server starts. I'll try investigate this so I can clarify the installation instructions.

**Comment by rcamp004** [comment]
Hi, I've just had the same issue as @quang-ha. In my case I did the following:
1. Stop running current kernel running in terminal with ctrl+c

2. Continuing in terminal I then ran:
 ```
jupyter nbextension enable --py gmaps
```

Output from terminal: 
```
Enabling notebook extension jupyter-gmaps/extension...
      - Validating: OK
```

started a new notebook kernel server by typing in Terminal 
```
jupyter notebook
```

The maps are now visible without the need to do a full restart on my system (mac running El Capitan).

**Comment by pbugnion** [comment]
Thanks for this.

Yes, you definitely need to restart the Jupyter server for the changes caused by running `jupyter nbextension enable --py gmaps` to work.

In principle, it would be good to be able to give feedback to the user if they have not enabled the JavaScript extension. I think this would need to live in ipywdgets, not gmaps directly, though.

**Comment by RymMichaut** [comment]
haha, got exactly the same problem, restarted the computer and got my map :)
thank you

**Comment by plasmonresonator** [comment]
> Hi, I've just had the same issue as @quang-ha. In my case I did the following:
> 
> 1. Stop running current kernel running in terminal with ctrl+c
> 2. Continuing in terminal I then ran:
> 
> ```
> jupyter nbextension enable --py gmaps
> ```
> Output from terminal:
> 
> ```
> Enabling notebook extension jupyter-gmaps/extension...
>       - Validating: OK
> ```
> started a new notebook kernel server by typing in Terminal
> 
> ```
> jupyter notebook
> ```
> The maps are now visible without the need to do a full restart on my system (mac running El Capitan).

This fixed it for me.  Thank you!

**Comment by LuddeEklund** [comment]
Well, there are different paths for Anaconda user:
C:\User\1 

and for administrator

C:\Windows\system32

Anaconda installed for one user and 64 bit. Not solved yet

**Comment by Ei-Thandar-Aung** [comment]
![Screenshot (48)](https://user-images.githubusercontent.com/46325502/60517166-34569e80-9d05-11e9-9d79-7b7e75cf82d9.png)
 I run jupyter nbextension enable --py gmaps. But i have validating problem like in photo

**Comment by Ei-Thandar-Aung** [comment]
![Screenshot (48)](https://user-images.githubusercontent.com/46325502/60517166-34569e80-9d05-11e9-9d79-7b7e75cf82d9.png)
 I run jupyter nbextension enable --py gmaps. But i have validating problem like in photo

**Comment by Abdul15588** [comment]
I was Having the Same Issue... But When i waited for a while it started showing the maps itself So need to worry just  take a breath Restart the Kernal And Wait for the plots more than usual

**Comment by reza-ya57** [comment]
> Hi, I've just had the same issue as @quang-ha. In my case I did the following:
> 
> 1. Stop running current kernel running in terminal with ctrl+c
> 2. Continuing in terminal I then ran:
> 
> ```
> jupyter nbextension enable --py gmaps
> ```
> 
> Output from terminal:
> 
> ```
> Enabling notebook extension jupyter-gmaps/extension...
>       - Validating: OK
> ```
> 
> started a new notebook kernel server by typing in Terminal
> 
> ```
> jupyter notebook
> ```
> 
> The maps are now visible without the need to do a full restart on my system (mac running El Capitan).

I had same issue and follow your instruction and it is fixed now 👍 Thanks.

**Comment by kbehyar** [comment]
> 

You are an absolute genius. I wasted 3 hours of my time and didn't realize restarting the kernel was the issue.
