### ISSUE TITLE
Earthquake data not the same shape as other datasets

### ISSUE THREAD

**Issue by AndreaCrotti** [pbugnion/gmaps#82]
The earthquake dataset is a list of triples, so it breaks when passing it to the HeatMap.

**Comment by pbugnion** [comment]
Yes, it's meant to be plotted as a weighted heatmap:

```python
earthquakes = gmaps.datasets.load_dataset('earthquakes')
m = gmaps.Map()
heatmap = gmaps.WeightedHeatmap(data=earthquakes)
m.add_layer(heatmap)
m
```

`WeightedHeatmap` expects a data array of shape `[ (lat, long, weight),  ... ]`

I appreciate that the interface is confusing at the moment so, ultimately, it would make sense to unify the heatmap and weighted heatmap layers into a single function that looks something like:

```python
def heatmap_layer(coordinates, weights=None, opacity=..., ...):
    if weights is not None:
        return WeightedHeatmap()
    else:
        return Heatmap()
```
