### ISSUE TITLE
Ability to set centre and zoom options on basic map

### ISSUE THREAD

**Issue by pbugnion** [pbugnion/gmaps#83]
It would be good to be able to set the centre and zoom on maps (cf issue #80). An interface like:

``` python
m = Map(zoom=8, centre=[-5.0, 5.0], centre_on_data=False)
```

would work. The `centre_on_data` argument is useful to stop the default behaviour which recanters the map so it always bounds the data.

**Comment by csala** [comment]
I need to point out that currently there actually is a way to set these options, even though it's kind of a hack:

```
fig = gmaps.figure()

# Add any layers before the next step

fig._map.data_bounds = [
    (min_lat, min_long),
    (max_lat, max_long)
]
fig
```

But, again: this is just a shortcut to make it work until the right implementation is in place.

**Comment by pbugnion** [comment]
Thanks for this -- it's very very useful to have workarounds for missing features.

**Comment by pbugnion** [comment]
This is now implemented:

```python
gmaps.figure(center=(40.75, -74.00), zoom_level=12)
```

`center` and `zoom_level` must either be *both* specified, or neither. In the case where neither are specified, the figure as behaves as before: centering on the data.

**Comment by CMCDragonkai** [comment]
What exactly is a zoom level? Is it some factor on height/elevation of the
camera? Then does camera dimensions also matter for field of view?

**Comment by pbugnion** [comment]
> What exactly is a zoom level?

That's a good question. The zoom level is an *integer* between 0 and 21 that gets given directly to the Google Maps API (see [the Google Maps documentation](https://developers.google.com/maps/documentation/javascript/tutorial#zoom-levels)). It is, as you say, a factor of height / elevation of the camera (conceptually at least).

> Then do camera dimensions also matter for field of view

The width and height of the map do matter for the field of view.

I think this is the least surprising implementation, but I'm open to adding other ways of calculating the map bounds if there is demand for it.
