### ISSUE TITLE
The ability to load arbitrary data sets

### ISSUE THREAD

**Issue by gregv21v** [pbugnion/gmaps#87]
It would be great to have api support that allows you add any data set you want instead of just the few added.

**Comment by pbugnion** [comment]
You can already use arbitrary data:

```python
import gmaps
m = gmaps.Map()
rows = [ # (latitude, longitude) pairs
    (5.0, 10.0),
    (-5.0, -10.0),
    (10.0, 20.0)
]
heatmap_layer = gmaps.Heatmap(data=rows)
m.add_layer(heatmap_layer)
m
```

Is this what you want or are you after something else?

**Comment by gregv21v** [comment]
I didn't realize you could do that.
