### ISSUE TITLE
"Oops! Something went wrong." with weighted heat map layer.

### ISSUE THREAD

**Issue by andmib** [pbugnion/gmaps#93]
I am passing a list of tuples to gmaps.WeightedHeatmap. When I display the widget, the heat map briefly displays in my console and then immediately grays out with the error message "Oops! Something went wrong. This page didn't load Google Maps correctly. See the JavaScript console for technical details."

Any suggestions?

**Comment by pbugnion** [comment]
Did you close this because it was resolved?

If not, I suspect the problem is that you have not authenticated with Google maps. See [this](http://jupyter-gmaps.readthedocs.io/en/latest/authentication.html) for how to authenticate.

**Comment by andmib** [comment]
Hey, thanks for the reply. It is resolved. I figured out that is was an authentication problem :/

**Comment by pbugnion** [comment]
:+1:
